### ISSUE TITLE
Requesting help installing c++ language support with intellisense for Oni [Help Wanted]

### ISSUE THREAD

**Issue by adabo** [onivim/oni#1570]
I'm having difficulty setting this up. I couldn't find instructions. It's over my head, to be honest.

I read that I should install clangd, which then lead me to install LLVM. Another vague instruction was what to put in Oni config file. I am not familiar with Oni config files.

I'm not even sure what I'm doing. I could be trying to do something that is not what I want.

The only IDE I've used was Visual Studio. It works with c++ out of the box and shows me everything I need to know about my code. And it runs my code and tells me if there are problems.

So what is the language support for Oni for? And how do I enable it?

Thank you for your time. The project looks promising.

**Comment by adabo** [comment]
I received some assistance in the Oni chat lobby. I was able to configure the config.js correctly only to find it still wasn't working. The path variable is set and running clangd in cmd works fine.

But that was all in a standard user account (Windows 10). So I switched to the admin account and something happened. I saw a red line as I was typing and some tooltips each word I typed. But then it just stopped after the first line and left a red circle with a ! at the end of the line.

I tried again creating a new cpp file and again it shows the red line where I type and the tooltips. Then it fails again after the first line.

Not sure what's going on nor what to do. I just wish I didn't have to log into the administrator account.

**Comment by TalAmuyal** [comment]
@adabo, might it be that you installed `clang` only for the current user?
It is possible that the "current user" in the installation phase is an admin, that will explain why it is recognized for your admin account, but not for your regular account.

**Comment by adabo** [comment]
What I did was install Oni with standard account and selected for all users.

I can try installing with admin account.

But that still leaves us with the broken intellisense.

**Comment by TalAmuyal** [comment]
I mean installing `clang` with `all users`.

Regarding the `broken intellisense`, I think it is a known issue that already has an open bug report.
If this is it, then the "intelisense" is randomly crashing.
I'm not sure if it is already fixed in master or not though...

**Comment by adabo** [comment]
Ah yes, I confused the installers. LLVM does ask for all users. Apologies.

I fixed the standard account by first logging into Admin and uninstalling LLVM and Oni. Afterwards I reinstalled them both (LLVM with all users), and rebooted afterwards. The intellisense is showing now, but again, the bug.

Thanks for the assistance!

**Comment by TalAmuyal** [comment]
Seems like in https://github.com/onivim/oni/pull/1513 and https://github.com/onivim/oni/issues/1441 there was a similar talk about the LSP stop working.

@adabo, could you open the DevTools and try to identify and post logs that might be relevant? (for instance, an exception that might be related the the Language Server Protocol or to `clangd`)

**Comment by adabo** [comment]
Sure. I can try that.

**Comment by adabo** [comment]
I made a new discovery. Intellisense fails if the first line you type is a complete #include statement .eg "#include <iostream>". Press <Enter> and intellisense is dead. It seems you can start the first line with anything else and intellisense will continue working.

The steps as follows:

- Start Oni
- Load an empty cpp file
- Type "#include <iostream>" and press <Enter>
- From this point on intellisense fails for all files untill you restart Oni
- Restart Oni
- Load an empty cpp file
- Type "#in" and press <Enter> or <Tab>
- Intellisense appears to work from this point on

Log for intellisense fail and [video](https://drive.google.com/open?id=1dsSYPPq-Yl_Do26_H_-0KeygcHJinpjy):

[Log](https://drive.google.com/open?id=1x4dKyYotR2bjDOg8IMBYz7WIgoqmkRvx) (Sorry, code markdown would not work for this log)

Log for no fail and [Video](https://drive.google.com/open?id=19kPH-RHEHSTt3b1WXV_HSwSAeqmAjn2l):

`bundle.js:1 [Language Client] Notification textDocument/didChange - C:\Users\Abel\Desktop\a.cpp: start
C:\Program Files (x86)\Oni\resources\app\node_modules\vscode-jsonrpc\lib\main.js:138 Uncaught (in promise) Error: Connection is closed.
    at new ConnectionError (C:\Program Files (x86)\Oni\resources\app\node_modules\vscode-jsonrpc\lib\main.js:138:28)
    at throwIfClosedOrDisposed (C:\Program Files (x86)\Oni\resources\app\node_modules\vscode-jsonrpc\lib\main.js:613:19)
    at Object.sendNotification (C:\Program Files (x86)\Oni\resources\app\node_modules\vscode-jsonrpc\lib\main.js:667:13)
    at l.<anonymous> (file:///C:/Program%20Files%20(x86)/Oni/resources/app/lib/browser/0.bundle.js:182:60950)
    at Generator.next (<anonymous>)
    at a (file:///C:/Program%20Files%20(x86)/Oni/resources/app/lib/browser/0.bundle.js:182:59259)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ConnectionError @ C:\Program Files (x86)\Oni\resources\app\node_modules\vscode-jsonrpc\lib\main.js:138
throwIfClosedOrDisposed @ C:\Program Files (x86)\Oni\resources\app\node_modules\vscode-jsonrpc\lib\main.js:613
sendNotification @ C:\Program Files (x86)\Oni\resources\app\node_modules\vscode-jsonrpc\lib\main.js:667
(anonymous) @ 0.bundle.js:182
a @ 0.bundle.js:182
_tickCallback @ internal/process/next_tick.js:188`

**Comment by TalAmuyal** [comment]
Wow, thanks for investing in a YouTube video!
Actually, it really helps (one picture is worth a thousand words, one video is priceless).

Tried it as well, seams that I get an exception for every other keystroke (though I still get the completions).

Also, it seems that the exception is thrown in the `vscode-jsonrpc`, I wonder if it's Oni's fault or clangd's.
Anyway, I can try and have a look tomorrow - but I am not too familiar with that area, so no promises here.

**Comment by adabo** [comment]
You're more than welcome. It's the leas I can do. I'm sure you're you'll figure something out. Programmers are problem solvers :)

**Comment by Bubesh958** [comment]
@adabo dude, help me out configuring oni for c++. I installed LLVM, clangd works in cmd. But I don't know how to configure oni to do code completion.
