### ISSUE TITLE
Oni does not launch Neovim.

### ISSUE THREAD

**Issue by jordan-arenstein** [onivim/oni#2396]
**Oni Version:** 0.3.6
**Neovim Version (Linux only):**
**Operating System:** macOS Mojave Beta 2, and 3.

**Issue:** Oni cannot launch neovim instance on open. Instead, it shows a screen "Uh oh! Unable to launch Neovim... Neovim v0.2.1 is required to run Oni. This has persisted through clean installs of neovim 0.3.0, 0.2.1, and builds of Oni from Homebrew Cask and Github releases.

Oni 0.3.4 works fine.

**Expected behavior:** Oni launches and shows neovim interface.

**Actual behavior:** Oni shows error screen.

**Steps to reproduce:** Open Oni.

**Comment by jordan-arenstein** [comment]
Looks like this is very similar to #2354, my bad for missing that. However, I am running macOS 10.14. Sorry if this counts as a duplicate.

**Comment by CrossR** [comment]
I'm running the same OS as you and can confirm it looks to be the same as #2354. Downgrading to neovim `0.2.2` worked fine for me, but I'm less sure why `0.3.0` isn't working, nor the `0.3.1` nightly.

**Comment by jordan-arenstein** [comment]
I just followed your advice in #2354 to set debug.neovimPath, and it works for me with 0.3.0 and 0.2.1, by setting it to my brew directory:

    "debug.neovimPath": "/usr/local/Cellar/neovim/0.3.0/bin/nvim",

Alternating between 0.2.1 and 0.3.0, it seems fine now.

**Comment by jeffling** [comment]
@jordan-arenstein interesting, that didn't work for me.

**Comment by jeffling** [comment]
@CrossR   Perfect. It's weird for me because I don't have a config.js, I suppose I'll just create it for now.

**Comment by jwmann** [comment]
I also have this issue with the public version of Mojave 10.14 and `"debug.neovimPath": "/usr/local/Cellar/neovim/0.3.1/bin/nvim"` inside the config fixed it.

However, I do think this should be fixed so that we don't have to set this config.

**Comment by olalonde** [comment]
Where's that mysterious `config.js` file located? I could only find `~/.config/oni/config.tsx`

**Comment by jordan-arenstein** [comment]
@olalonde The `config.tsx` file is a typescript file, which compiles to the `config.js` file. Using either is fine. You can add the same line to either.

**Comment by olalonde** [comment]
@jordan-arenstein I added the line to `config.tsx` but still getting the same error when opening Oni.. also there isn't any `.js` files in that folder at least

**Comment by jordan-arenstein** [comment]
Oh my bad! A reply [further above](https://github.com/onivim/oni/issues/2396#issuecomment-402778981) sorts this out. Creating a default config.js with that line should work. I'll look around for you.

**Comment by olalonde** [comment]
Fixed by creating `~/.config/oni/config.js` with following content:

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.activate = function (oni) {
		console.log("config activated");
		// Input
		//
		// Add input bindings here:
		//
		oni.input.bind("<c-enter>", function () { return console.log("Control+Enter was pressed"); });
		//
		// Or remove the default bindings here by uncommenting the below line:
		//
		// oni.input.unbind("<c-p>")
};
exports.deactivate = function (oni) {
		console.log("config deactivated");
};
exports.configuration = {
		//add custom config here, such as
		"ui.colorscheme": "nord",
		//"oni.useDefaultConfig": true,
		//"oni.bookmarks": ["~/Documents"],
		//"oni.loadInitVim": false,
		//"editor.fontSize": "12px",
		//"editor.fontFamily": "Monaco",
		// UI customizations
		"ui.animations.enabled": true,
		"ui.fontSmoothing": "auto",
		// https://github.com/onivim/oni/issues/2396#issuecomment-426767185
		"debug.neovimPath": "/usr/local/Cellar/neovim/0.3.1/bin/nvim",
};
```

**Comment by direvus** [comment]
@jordan-arenstein could Oni fall back gracefully to the system nvim if the bundled nvim fails?  If there is an `nvim` in the PATH, maybe just try running it and see what happens?

FWIW I was able to work around the issue just by putting `"debug.neovimPath": "/usr/local/bin/nvim"` into my config.js, which is a symlink to the brew install.

**Comment by mikepc** [comment]
I experienced this problem and added 

`  "debug.neovimPath": "/usr/local/Cellar/neovim/0.3.0/bin/nvim", `
to **~/config/oni/config.tsx**

This solved the issue for me

**Comment by bryphe** [comment]
Thanks for the investigation @jordan-arenstein and workaround @olalonde !

**Comment by goerz** [comment]
I tried the workaround in https://github.com/onivim/oni/issues/2396#issuecomment-430533798, which fixed the message initially. However, I'm the not able to open any file (nothing ever shows up in the right editor pane). When I hit cmd-Q, the app does not quit, but I'm again getting the "Uh oh! Unable to launch Neovim..." message in the editor pane.

This is Oni 0.3.6 on macOS Mojave 10.14.2 (18C54) and NVIM v0.3.2-dev installed through homebrew.

**Comment by bryphe** [comment]
FYI - the 0.3.9 release has a fix for this: https://github.com/onivim/oni/releases/tag/v0.3.9 

Recommend upgrading to that build (it was fixed in #2682 , which was included in 0.3.9)

**Comment by badosu** [comment]
Closing this in favor of #2706. Let us know if it's a different issue.
